ARG ELK_VERSION

# https://github.com/elastic/kibana-docker #6.6.2
# FROM docker.elastic.co/kibana/kibana-oss:${ELK_VERSION}
FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}
# PORT 5601

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
