ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker #6.6.2
#FROM docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu

# FROM blacktop/elasticsearch:${ELK_VERSION}